services:
  mongodb:
    image: mongo:7-jammy
    container_name: ragforge-mongodb

    ports:
      - '27007:27017'

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - ragforge_mongodb_data:/data/db

    networks:
      - ragforge-network

    restart: always

networks:
  ragforge-network:

volumes:
  ragforge_mongodb_data: