"""create vector records pgvector table

Revision ID: 20260606_0002
Revises: 20260605_0001
Create Date: 2026-06-06
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '20260606_0002'
down_revision = '20260605_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vector_records (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            vector_record_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
            collection_name varchar(150) NOT NULL,
            record_id varchar(255) NOT NULL,
            text text NOT NULL,
            embedding vector NOT NULL,
            vector_size integer NOT NULL,
            embedding_model varchar(255) NOT NULL,
            embedding_provider varchar(100) NOT NULL,
            project_id varchar(255),
            asset_id varchar(255),
            chunk_id varchar(255),
            chunk_order integer,
            metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz,
            CONSTRAINT uq_vector_records_uuid UNIQUE (vector_record_uuid),
            CONSTRAINT uq_vector_records_collection_record_model UNIQUE (
                collection_name,
                record_id,
                embedding_provider,
                embedding_model,
                vector_size
            ),
            CONSTRAINT ck_vector_records_collection_not_blank
                CHECK (char_length(btrim(collection_name)) > 0),
            CONSTRAINT ck_vector_records_record_id_not_blank
                CHECK (char_length(btrim(record_id)) > 0),
            CONSTRAINT ck_vector_records_text_not_blank
                CHECK (char_length(btrim(text)) > 0),
            CONSTRAINT ck_vector_records_vector_size_positive
                CHECK (vector_size > 0),
            CONSTRAINT ck_vector_records_embedding_dimensions
                CHECK (vector_dims(embedding) = vector_size),
            CONSTRAINT ck_vector_records_embedding_model_not_blank
                CHECK (char_length(btrim(embedding_model)) > 0),
            CONSTRAINT ck_vector_records_embedding_provider_not_blank
                CHECK (char_length(btrim(embedding_provider)) > 0),
            CONSTRAINT ck_vector_records_chunk_order_non_negative
                CHECK (chunk_order IS NULL OR chunk_order >= 0)
        )
        """
    )

    op.create_index('ix_vector_records_collection_name', 'vector_records', ['collection_name'])
    op.create_index('ix_vector_records_vector_size', 'vector_records', ['vector_size'])
    op.create_index('ix_vector_records_project_id', 'vector_records', ['project_id'])
    op.create_index('ix_vector_records_asset_id', 'vector_records', ['asset_id'])
    op.create_index('ix_vector_records_chunk_id', 'vector_records', ['chunk_id'])
    op.create_index('ix_vector_records_embedding_model', 'vector_records', ['embedding_model'])
    op.create_index('ix_vector_records_embedding_provider', 'vector_records', ['embedding_provider'])
    op.create_index(
        'ix_vector_records_collection_vector_size_model',
        'vector_records',
        ['collection_name', 'vector_size', 'embedding_provider', 'embedding_model'],
    )
    op.create_index(
        'ix_vector_records_metadata_gin',
        'vector_records',
        ['metadata'],
        postgresql_using='gin',
    )

    # The approximate vector index is intentionally provider-managed in Branch 21 v4.
    # Reason: the embedding column uses pgvector's variable-dimension `vector` type.
    # PgVector requires expression/partial indexes for rows with a specific dimension.
    # The provider creates a safe index such as:
    #   embedding::<PGVECTOR_INDEX_VECTOR_TYPE>(<PGVECTOR_EFFECTIVE_VECTOR_SIZE>) vector_cosine_ops
    #   WHERE vector_size = <PGVECTOR_EFFECTIVE_VECTOR_SIZE>


def downgrade() -> None:
    op.drop_index('ix_vector_records_metadata_gin', table_name='vector_records')
    op.drop_index('ix_vector_records_collection_vector_size_model', table_name='vector_records')
    op.drop_index('ix_vector_records_embedding_provider', table_name='vector_records')
    op.drop_index('ix_vector_records_embedding_model', table_name='vector_records')
    op.drop_index('ix_vector_records_chunk_id', table_name='vector_records')
    op.drop_index('ix_vector_records_asset_id', table_name='vector_records')
    op.drop_index('ix_vector_records_project_id', table_name='vector_records')
    op.drop_index('ix_vector_records_vector_size', table_name='vector_records')
    op.drop_index('ix_vector_records_collection_name', table_name='vector_records')
    op.drop_table('vector_records')
